### PR TITLE
feat: dont embed links in code snippets

### PR DESCRIPTION
**Pull request by MilkeeyCat**
Exactly what title says. this regex will look for links which are NOT surrounded by ```

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Does this also work for only two backtick snippets? Does it work for multiple lines?

Is applying this regex the best way? Do we also need it for pings and emotes and image emends in code snippets then?

**Comment by ChillerDragon** [comment]
Also what about a link between two code snippets? My regex is too bad to see if that would break.

**Comment by MilkeeyCat** [comment]
image
it doesn't work when the link is between two code snippets :(

**Comment by ChillerDragon** [comment]
Yea maybe we need something stronger than regex for that ._.

**Comment by MilkeeyCat** [comment]
> Yea maybe we need something stronger than regex for that ._.

i think its possible, like if you really want you can write linux kernel in regexes.

**Comment by MilkeeyCat** [comment]
image

**Comment by MilkeeyCat** [comment]
it works good if you write it as normal human being but if you try to write somethign like ``` `` https://localhost `` ``` it doesnt work

**Comment by MilkeeyCat** [comment]
image
now it does work :smirk:

**Comment by ChillerDragon** [comment]
Okay we can give it a try. I might refactor or revert it at some point. Especially when I start fixing pings breaking stuff too.

I do not understand how the single backtick in your regex manages to correctly check all those cases.
Also is there any chance you could more descriptive variables names than g0, g1, g2...

Does it also work for single backticks in front that do not display a code block. For example a message like this:

` https://chat.zillyhuhn.com/

**Comment by MilkeeyCat** [comment]
image
it looks like this when i write ` https://localhost:42069 so it works, ig? Also what names would you like to see there. Those are regex groups. `group1`, `group2`?

**Comment by ChillerDragon** [comment]
Ready to merge then?

**Comment by MilkeeyCat** [comment]
idk :justatest: ure da boss here

**Comment by ChillerDragon** [comment]
Yea any chance you can come up with more descriptive vars than g0, g1 etc

```
        new RegExp(/(`+)(.*?)(\1)|(https?:\/\/[a-zA-Z0-9\-_\[\]\?\#\:\&\$\+\*\%\/\.\=\@]+)/ig),
        (g0, g1, g2, g3, url) => {
```

**Comment by ChillerDragon** [comment]
Thanks

**Pull request merged**
